variable "project" {}
variable "region" {}
variable "subnet_name" {}
variable "vpc_id" {}
variable "cidr_range" {}
variable app_prefix {}
#variable "sec_range2" {}
#variable "sec_range3" {}
#variable "sec_cidr_range" {}