---
- hosts: My_Group
  become: yes
  become_method: sudo
  gather_facts: false

  tasks:
    - name: Update APT Cache
      become: yes
      apt:
        update_cache: yes
        force_apt_get: yes
          
    - name: Remove apt lock file
      become: yes
      file:
        state: absent
        path: "/var/lib/dpkg/lock"


    - name: Install required Ubuntu packages
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - openjdk-11-jdk

  
    - name: ensure the jenkins apt repository key is installed
      apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
      become: yes

    - name: ensure the repository is configured
      apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
      become: yes

    - name: ensure jenkins is installed
      apt: name=jenkins update_cache=yes
      become: yes

    - name: ensure jenkins is running
      service: name=jenkins state=started

    - name: Start & Enable Jenkins
      service: 
        name: jenkins
        state: started

    - name: Sleep for 30 seconds and continue with play
      wait_for: 
        timeout: 30

    - name: Get init password Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: Print init password Jenkins
      debug:
        var: result.stdout

    - name: APT - Add Docker GPG key
      apt_key: 
        keyserver: keyserver.ubuntu.com 
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker packages
      apt:
        name: ['docker-ce','docker-ce-cli','containerd.io']
        state: present      

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
        update_cache: yes
     
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
 
    - name: Install kubectl with option --classic
      snap:
        name: kubectl
        classic: yes

    - name: install git
      apt: package=git update_cache=yes 


    - name: Allow wheel group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%jenkins'
        line: 'jenkins ALL= NOPASSWD: ALL'

    - name: Restart Jenkins if required
      service:
        name: jenkins
        state: restarted
    - name: Start jenkins service
      service:
        name: jenkins
        state: started 